---
title: "ST512-SP26-Homework-6"
author: "Jason Menjivar-Hernandez"
format: pdf
editor: visual
---

## Problem 1

**a**

$H_o: \sigma_{\alpha}^2$ = 0

$H_A: \sigma_{\alpha}^2$ \> 0

F.value = $\frac{MSA}{MSE}$ = 238.7

p.value $\approx$ 0.0000

Reject null hypothesis. There is strong evidence that mean sodium content is NOT the same in all brands.

**b**

$\bar{y}_{1.} \approx$ 23.64 mg

$\bar{y}_{2.} \approx$ 10.68 mg

**c**

$\sigma^2$ = MSE = 0.72

$\hat{\sigma}_\mu$ = $S^2_\mu$ = $\frac{MS_{Tr}-MSE}{n}$ = $\frac{170.91-0.72}{8}$ = 21.274

**d**

$\hat{p}$ = $\frac{21.274}{0.72+21.274}$ = 0.967

Therefore, approximately 97% of variation in the sodium content is due to the different brands.

## Problem 2

**a**

| Source  | df  | SS   | MS     | F-value |
|---------|-----|------|--------|---------|
| Rater   | 7   | 1641 | 234.43 | 5.018   |
| Product | 4   | 892  | 223.00 | 4.772   |
| R * P  | 28  | 1308 | 46.71  | 6.362   |
| Error   | 120 | 881  | 7.34   |         |

**b**

$\sigma^2$ = MSE = 7.3417

$\sigma^2_{\alpha \beta}$ = $\frac{MS_{R*P}-MSE}{n}$ = $\frac{46.7143-7.3417}{4}$ = 9.8432

$\sigma^2_{\alpha}$ = $\frac{MS_{R}-MS_{R*P}}{bn}$ = $\frac{234.4286-46.7143}{5*4}$ = 9.3857

$\sigma^2_{\beta}$ = $\frac{MS_{P}-MS_{R*P}}{an}$ = $\frac{223.00-46.7143}{8*4}$ = 5.5089

## Problem 3

**a**

| Source   | df  | SS       | MS     | F-value | p-value |
|----------|-----|----------|--------|---------|---------|
| Location | 1   | 1.30     | 1.30   | 0.036   | 0.853   |
| Player   | 9   | 3879.30  | 431.03 | 11.99   | 0.0005  |
| P * L   | 9   | 323.67   | 35.96  | 0.73    | 0.682   |
| Error    | 320 | 15787.29 | 49.34  |         |         |
| Total    | 339 | 19991.56 |        |         |         |

**b**

$H_o: \sigma^2_{\alpha \beta} = 0$

$H_A: \sigma^2_{\alpha \beta} > 0$

$F = \frac{MS_{PL}}{MSE}$ = $\frac{35.9633}{49.3353}$ = 0.7290

p-value = 0.6823

p-value > 0.05 --> fail to reject $H_o$

Therefore, there is no significant interaction between player and location.

**c**

$H_o: \alpha_1 = \alpha_2 = 0$ 

$H_A: \alpha_i \neq  0$ 

$F = \frac{MS_{L}}{MSE}$ = $\frac{1.30}{49.3353}$ = 0.0264

p-value = 0.129

p-value > 0.05 --> fail to reject null

Therefore, there is no significant main effect due to location. 

**d**

$H_o: \sigma^2_{\beta} = 0$ 

$H_A: \sigma^2_{\beta} > 0$ 

$F = \frac{MS_{player}}{MS_{P*L}}$ = $\frac{431.0333}{35.9633}$ = 11.9854

p-value = 0.0005

p-value < 0.005, reject null 

Therefore, there is a significant player main effect. 

**e**

$\sigma^2 = MSE = 49.3353$ 

$\hat{\sigma}^2_{\alpha \beta}$ = $\frac{MS_{P*L}-MSE}{n}$ = $\frac{35.9633-49.3353}{17}$ = -0.7866 

$\hat{\sigma}^2_{\beta}$ = $\frac{MS_{player}-MS_{P*L}}{an}$ = $\frac{431.0333-35.9633}{2*17}$ = 11.6197 

## Problem 4 


